### ISSUE TITLE
Review Table Wrapping Toggle for re-implementation

### ISSUE THREAD

**Issue by mitchelljfranklin** [mitchelljfranklin/Boomi-Platform-Extension#25]
YourLocalRuntime — Today at 8:41 AM
I can't right now, I'm not on it. But the behavior is this.

Every time I go into process reporting, the table wrap is on.

I hover over and click toggle table wrap. My expectation (for right or wrong) is that it turns the wrap off and it stays off.

What ends up happening for me is that the toggle only works while I have the process reporting tab open.

Reading Matt's comment - it appears my assumption is flawed
matt – sacramento — Today at 8:41 AM
@mitchellfranklin maybe we save the past state in the Chrome store so it will persist?
Or we set a setting for the default... on/off and you can toggle from there... 🤔

**Comment by matt-flaig** [comment]
Implemented new options in the 1.7.4.5 branch:
- Never Wrap (Default)*
- Always Wrap
- Toggle on Header Hover

*this field is the Boomi default, for users using the extension already, they will be opted in to the "Toggle on Header Hover" until they next save their Extension preferences.

This allows user to select one state permanently (rather than having to always toggle off if they prefer no wrapping).

**Note:** The state of the Toggle wrap is still not synced across sessions (page reloads) or tabs. I tried to implement it but it would be a much larger effort due to not be able to access chrome.storage in the tablewrap.js file.
